#
# Copyright 2019, Intel Corporation
#
# 'recipe' for Docker to build an Debian package
#
# Pull base image
FROM ubuntu:18.04
Maintainer John.E.Malmberg <John.E.Malmberg@intel.com>

# Install basic tools
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
            autoconf bash curl debmake debhelper dpkg-dev doxygen gcc \
            git locales make patch rpm

# FUSE3
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
            pkg-config udev python3 python3-pytest

# Fuse 3 need meson > 0.46 so pull from Ubuntu 18.10
ENV UBUNTU_URL="https://launchpad.net/ubuntu/+archive/primary/+files"
RUN curl -sS -f -L -O ${UBUNTU_URL}/meson_0.47.2-1ubuntu2_all.deb ;\
   apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      ./meson_0.47.2-1ubuntu2_all.deb

# force an upgrade to get any newly built packages
ARG CACHEBUST=1
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y; \
    apt-get autoremove -y
